name: Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting with Prettier
        run: pnpm prettier --check "**/*.{js,ts,jsx,tsx,astro,md,mdx,json,css,yml}"

      - name: Run ESLint
        run: pnpm lint

      - name: Run spellcheck
        run: pnpm cspell --no-progress "src/blog/**/*.{md,mdx}" "src/projects/**/*.{md,mdx}" "src/pages/**/*.astro"
